### ISSUE TITLE
Just for your information....

### ISSUE THREAD

**Issue by ghost** [MiDoNaSR545/MiDoNaSR545#1]
I'm sure you know it, but the "Profile views" thing you have in your README.md is very heavily skewed.

**Comment by MiDoNaSR545** [comment]
> I'm sure you've realised it, but the "Profile views" thing you have in your README.md is very heavily skewed.

Tbh idk how it raised like this i havnt used any hack but will use another working one😁

**Comment by ghost** [comment]
I'd personally not have a profile view counter at all. One person can visit your profile multiple times, and those multiple visits would be counted, so it seems somewhat pointless.
